DROP TABLE IF EXISTS GESTOCK_API_BEEGO_INVENTARIO.inventario.ajustes;
DROP TABLE IF EXISTS GESTOCK_API_BEEGO_INVENTARIO.inventario.categoria_producto;
DROP TABLE IF EXISTS GESTOCK_API_BEEGO_INVENTARIO.inventario.inventario_productos;
DROP TABLE IF EXISTS GESTOCK_API_BEEGO_INVENTARIO.inventario.inventario;
DROP TABLE IF EXISTS GESTOCK_API_BEEGO_INVENTARIO.inventario.movimientos;
DROP TABLE IF EXISTS GESTOCK_API_BEEGO_INVENTARIO.inventario.productos;
DROP TABLE IF EXISTS GESTOCK_API_BEEGO_INVENTARIO.inventario.tipo_movimiento;
DROP TABLE IF EXISTS GESTOCK_API_BEEGO_INVENTARIO.inventario.transferencia;

DROP SCHEMA IF EXISTS GESTOCK_API_BEEGO_INVENTARIO;