appname = empresa
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:postgres@localhost:5432/time_2?sslmode=disable&search_path=empresa
