swagger: "2.0"
info:
  title: beego Test API
  description: |
    beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /guias_entrada/:
    get:
      tags:
      - guias_entrada
      description: |-
        get GuiasEntrada
        <br>
      operationId: GuiasEntradaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.GuiasEntrada'
        "403":
          description: ""
    post:
      tags:
      - guias_entrada
      description: |-
        create GuiasEntrada
        <br>
      operationId: GuiasEntradaController.Post
      parameters:
      - in: body
        name: body
        description: body for GuiasEntrada content
        required: true
        schema:
          $ref: '#/definitions/models.GuiasEntrada'
      responses:
        "201":
          description: '{int} models.GuiasEntrada'
        "403":
          description: body is empty
  /guias_entrada/{id}:
    get:
      tags:
      - guias_entrada
      description: |-
        get GuiasEntrada by id
        <br>
      operationId: GuiasEntradaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.GuiasEntrada'
        "403":
          description: :id is empty
    put:
      tags:
      - guias_entrada
      description: |-
        update the GuiasEntrada
        <br>
      operationId: GuiasEntradaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for GuiasEntrada content
        required: true
        schema:
          $ref: '#/definitions/models.GuiasEntrada'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.GuiasEntrada'
        "403":
          description: :id is not int
    delete:
      tags:
      - guias_entrada
      description: |-
        delete the GuiasEntrada
        <br>
      operationId: GuiasEntradaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /proveedor_productos/:
    get:
      tags:
      - proveedor_productos
      description: |-
        get ProveedorProductos
        <br>
      operationId: ProveedorProductosController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ProveedorProductos'
        "403":
          description: ""
    post:
      tags:
      - proveedor_productos
      description: |-
        create ProveedorProductos
        <br>
      operationId: ProveedorProductosController.Post
      parameters:
      - in: body
        name: body
        description: body for ProveedorProductos content
        required: true
        schema:
          $ref: '#/definitions/models.ProveedorProductos'
      responses:
        "201":
          description: '{int} models.ProveedorProductos'
        "403":
          description: body is empty
  /proveedor_productos/{id}:
    get:
      tags:
      - proveedor_productos
      description: |-
        get ProveedorProductos by id
        <br>
      operationId: ProveedorProductosController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ProveedorProductos'
        "403":
          description: :id is empty
    put:
      tags:
      - proveedor_productos
      description: |-
        update the ProveedorProductos
        <br>
      operationId: ProveedorProductosController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for ProveedorProductos content
        required: true
        schema:
          $ref: '#/definitions/models.ProveedorProductos'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ProveedorProductos'
        "403":
          description: :id is not int
    delete:
      tags:
      - proveedor_productos
      description: |-
        delete the ProveedorProductos
        <br>
      operationId: ProveedorProductosController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /proveedores/:
    get:
      tags:
      - proveedores
      description: |-
        get Proveedores
        <br>
      operationId: ProveedoresController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Proveedores'
        "403":
          description: ""
    post:
      tags:
      - proveedores
      description: |-
        create Proveedores
        <br>
      operationId: ProveedoresController.Post
      parameters:
      - in: body
        name: body
        description: body for Proveedores content
        required: true
        schema:
          $ref: '#/definitions/models.Proveedores'
      responses:
        "201":
          description: '{int} models.Proveedores'
        "403":
          description: body is empty
  /proveedores/{id}:
    get:
      tags:
      - proveedores
      description: |-
        get Proveedores by id
        <br>
      operationId: ProveedoresController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Proveedores'
        "403":
          description: :id is empty
    put:
      tags:
      - proveedores
      description: |-
        update the Proveedores
        <br>
      operationId: ProveedoresController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Proveedores content
        required: true
        schema:
          $ref: '#/definitions/models.Proveedores'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Proveedores'
        "403":
          description: :id is not int
    delete:
      tags:
      - proveedores
      description: |-
        delete the Proveedores
        <br>
      operationId: ProveedoresController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.GuiasEntrada:
    title: GuiasEntrada
    type: object
    properties:
      Activo:
        type: boolean
      Estado:
        type: string
      FechaCreacion:
        type: string
        format: datetime
      FechaModificacion:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      IdBodega:
        type: integer
        format: int64
      IdProveedor:
        type: integer
        format: int64
  models.ProveedorProductos:
    title: ProveedorProductos
    type: object
    properties:
      Activo:
        type: boolean
      FechaCreacion:
        type: string
        format: datetime
      FechaModificacion:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      IdProducto:
        type: integer
        format: int64
      IdProveedor:
        type: integer
        format: int64
      Precio:
        type: number
        format: double
  models.Proveedores:
    title: Proveedores
    type: object
    properties:
      Activo:
        type: boolean
      Correo:
        type: string
      FechaCreacion:
        type: string
        format: datetime
      FechaModificacion:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      IdEmpresa:
        type: integer
        format: int64
      Nombre:
        type: string
      Telefono:
        type: string
tags:
- name: proveedores
  description: |
    ProveedoresController operations for Proveedores
- name: proveedor_productos
  description: |
    ProveedorProductosController operations for ProveedorProductos
- name: guias_entrada
  description: |
    GuiasEntradaController operations for GuiasEntrada
