appname = EMPRESA
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true

PGuser = ${EMPRESA_PGUSER}
PGpass = ${EMPRESA_PGPASS}
PGhost = ${EMPRESA_PGHOST}
PGport = ${EMPRESA_PGPORT}
PGdb   = ${EMPRESA_PGDB}
PGschema = ${EMPRESA_PGSCHEMA}

