appname = EMPRESA
httpport = ${empresa_HTTP_PORT}
runmode = ${empresa_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

PGuser = ${empresa_PGUSER}
PGpass = ${empresa_PGPASS}
PGhost = ${empresa_PGHOST}
PGport = ${empresa_PGPORT}
PGdb   = ${empresa_PGDB}
PGschema = ${empresa_PGSCHEMA}

