# HTTP_PORT = [Puerto de exposicion del api]
# RUN_MODE  = [Modo de ejecucion del API: dev | prod]

# Variables de la BD
# PG_USER   = [Usuario de BD]
# PG_PASS   = [Contraseña del usuario de la DB]
# PGHOST    = [URL, IP, DOMINIO o ENDPOINT de la DB]
# PGPORT    = [Puerto de la DB]
# PGDB      = [Nombre de la base de datos]
# PGSCHEMA  = [Nombre del esquema de base de datos]

appname         = api_compras
httpport        = ${api_compras_HTTP_PORT}
runmode         = ${api_compras_RUN_MODE}
autorender      = false
copyrequestbody = true
EnableDocs      = true

# Definicion de variables de entorno DB
PGuser   = ${api_compras_PG_USER}
PGpass   = ${api_compras_PG_PASS}
PGhost   = ${api_compras_PGHOST}
PGport   = ${api_compras_PGPORT}
PGdb     = ${api_compras_PGDB}
PGschema = ${api_compras_PGSCHEMA}
