appname = GESTOCK_API_BEEGO
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true



PGuser =${GESTOCK_API_BEEGO_PG_USER}
PGpass =${GESTOCK_API_BEEGO_PG_PASS}
PGhost =${GESTOCK_API_BEEGO_PGHOST}
PGport =${GESTOCK_API_BEEGO_PGPORT}
PGdb =${GESTOCK_API_BEEGO_PGDB}
PGschema =${GESTOCK_API_BEEGO_PGSCHEMA}