appname = GESTOCK_API_BEEGO_INVENTARIO
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true

PGuser = $ {GESTOCK_API_BEEGO_INVENTARIO_PGUSER}
PGpassword = $ {GESTOCK_API_BEEGO_INVENTARIO_PGPASSWORD}
PGhost = $ {GESTOCK_API_BEEGO_INVENTARIO_PGHOST}
PGport = $ {GESTOCK_API_BEEGO_INVENTARIO_PGPORT}
PGdatabase = $ {GESTOCK_API_BEEGO_INVENTARIO_PGDATABASE}
PGschema = $ {GESTOCK_API_BEEGO_INVENTARIO_PGSCHEMA}
